In [5]:
import pandas;
import numpy;
import seaborn as sns;
import matplotlib.pyplot as plt
import plotly.express as px
import folium
from folium.plugins import HeatMap

In [2]:
df = pandas.read_csv('tx_accidents.csv')
df.head()

,Unnamed: 0,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,261002,A-261009,Source2,2,2016-11-30 16:03:54,2016-11-30 17:20:00,30.336502,-97.755646,NaN,NaN,...,False,False,False,False,False,False,Day,Day,Day,Day
1,261003,A-261010,Source2,2,2016-11-30 16:32:18,2016-11-30 17:47:02,30.328165,-97.694305,NaN,NaN,...,False,False,False,False,False,False,Day,Day,Day,Day
2,261004,A-261011,Source2,2,2016-11-30 16:31:45,2016-11-30 17:46:34,30.326077,-97.692307,NaN,NaN,...,False,True,False,False,True,False,Day,Day,Day,Day
3,261005,A-261012,Source2,2,2016-11-30 16:06:49,2016-11-30 17:27:00,32.856014,-97.513084,NaN,NaN,...,False,False,False,False,False,False,Day,Day,Day,Day
4,261006,A-261013,Source2,3,2016-11-30 16:35:01,2016-11-30 17:49:39,32.797668,-97.212090,NaN,NaN,...,False,False,False,False,False,False,Day,Day,Day,Day

In [3]:
df.dropna()
df.drop_duplicates()
df = df.drop(["Unnamed: 0", "ID", "Source", "End_Lat", "End_Lng", "Civil_Twilight", "Nautical_Twilight", "Astronomical_Twilight"], axis=1)
df.head()

,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),Description,Street,City,County,...,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset
0,2,2016-11-30 16:03:54,2016-11-30 17:20:00,30.336502,-97.755646,0.01,Accident on RM-2222 Northland Dr at Mo Pac Exp...,Mopac Expy S,Austin,Travis,...,False,False,False,False,False,False,False,False,False,Day
1,2,2016-11-30 16:32:18,2016-11-30 17:47:02,30.328165,-97.694305,0.00,Accident on Grand Canyon Dr between Westheimer...,E Saint Johns Ave,Austin,Travis,...,False,False,False,False,False,False,False,False,False,Day
2,2,2016-11-30 16:31:45,2016-11-30 17:46:34,30.326077,-97.692307,0.00,Accident on Saint Johns Ave at Cameron Rd.,Cameron Rd,Austin,Travis,...,False,False,False,False,True,False,False,True,False,Day
3,2,2016-11-30 16:06:49,2016-11-30 17:27:00,32.856014,-97.513084,0.01,#2 lane blocked and right hand shoulder blocke...,Hanger Cutoff Rd,Fort Worth,Tarrant,...,False,False,False,False,False,False,False,False,False,Day
4,3,2016-11-30 16:35:01,2016-11-30 17:49:39,32.797668,-97.212090,0.01,#2 lane blocked and right hand shoulder blocke...,I-820 N,Fort Worth,Tarrant,...,False,False,False,False,False,False,False,False,False,Day

In [ ]:
color_scale = [(0, 'orange'), (1,'red')]

fig = px.scatter_mapbox(df, 
                        lat="Start_Lat", 
                        lon="Start_Lng",
                        hover_data="Description",
                        zoom=8, 
                        height=800,
                        width=800)

fig.update_layout(mapbox_style="open-street-map")
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()

In [6]:
# Create a folium map centered around the mean of the coordinates
map_center = [df['Start_Lat'].mean(), df['Start_Lng'].mean()]
mymap = folium.Map(location=map_center, zoom_start=5)

# Add a heatmap layer
HeatMap(df[['Start_Lat', 'Start_Lng']], radius=10, blur=5).add_to(mymap)

# Save the map as an HTML file
mymap.save("heatmap.html")